server:
  port: ${SERVER_PORT:8083}
  servlet:
    context-path: ${CONTEXT_PATH:/${spring.application.name}}

spring:
  application:
    name: movie-process-api
  jackson:
    default-property-inclusion: non_null

feign:
  tmdb-api:
    base-url: ${TMDB_BASE_URL_API:https://api.themoviedb.org/3}
    api-key: ${TMDB_API_KEY:''}

